# -*- coding: utf-8 -*-
"""EBAC - Tarefa - Lógica de programação com Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j6osMuN67sTXzhtj8o4V7cVufl1ffMtW

##Calculadora Matemática
"""

continuar = "s"

while continuar == "s":
    try:
        primeiro_numero = float(input("Digite o primeiro número: "))
        segundo_numero = float(input("Digite o segundo número: "))
        operacao = input("Digite a operação (+,-,*,/): ")

        if operacao == "+":
            print("O resultado da soma é:", primeiro_numero + segundo_numero)
        elif operacao == "-":
            print("O resultado da subtração é:", primeiro_numero - segundo_numero)
        elif operacao == "*":
            print("O resultado da multiplicação é:", primeiro_numero * segundo_numero)
        elif operacao == "/":
            if segundo_numero == 0:
                print("Erro: Não é possível dividir por zero!")
            else:
                print("O resultado da divisão é:", primeiro_numero / segundo_numero)
        else:
            print("Operação inválida. Por favor, use +, -, * ou /.")
    except ValueError:
        print("Erro: Entrada inválida. Por favor, digite números válidos.")
    except Exception as e:
        print(f"Ocorreu um erro inesperado: {e}")

    continuar = input("Deseja fazer outra conta? (s/n):")

print("Volte sempre!")